api:
  enabled: true

sources:
  host_metrics:
    type: host_metrics
    scrape_interval_secs: 15

  generate_uuid:
    type: exec
    command:
      - uuidgen
    mode: scheduled
    scheduled:
      exec_interval_secs: 3

sinks:
  publish_to_nats:
    type: nats
    connection_name: "vector"
    inputs:
      - generate_uuid
    encoding:
      codec: json
    url: "nats://localhost:4222"
    subject: "task.uuid"

  log:
    type: console
    inputs:
      - generate_uuid
    encoding:
      codec: json
    healthcheck: true